db.host=localhost
db.port=3306
db.name=crud_usuarios
db.username=root
db.password=secret

smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=owenbadel19@gmail.com
smtp.password=zxxw ldng cytt jyuy
smtp.from.address=owenbadel19@gmail.com
smtp.from.name=javaemail